### ISSUE TITLE
Issue with prep_UNMASC_VCF

### ISSUE THREAD

**Issue by javi-a-lopez** [pllittle/UNMASC#12]
Hello,

I am having an issue with the import_ANNO function, which might be an due to differences in the version of VEP (104) or the COSMIC database annotation (v96)?

`Import annotation file ...`
`Parse annotation ...`
`Process COSMIC ...`
`Error in `$<-.data.frame`(`*tmp*`, "CosmicIDs", value = NA) :`
`  replacement has 1 row, data has 0`
`Calls: <Anonymous> -> $<- -> $<-.data.frame`
`Execution halted`

Here are the first 100 lines from my annotated input file which I am using:
[anno_file_head.txt](https://github.com/pllittle/UNMASC/files/8996146/anno_file_head.txt)

Not really sure what could be causing the the issue or how to fix it. Please let me know if you have any idea what's causing this or if you need any additional information to figure it out.

Thanks,
Javier

**Comment by pllittle** [comment]
Hi @javi-a-lopez,

Thank you for your interest in UNMASC and thank you for the anno file. The first thing that jumps to my eye is #CHROM column. Could you append the "chr" to your contigs. A line in the function will filter on #CHROM values of chr1-chr22, chrX, and chrY.

Hope this helps!
