### ISSUE TITLE
Is possible tumor-only samples?

### ISSUE THREAD

**Issue by byeongill** [pllittle/UNMASC#3]
Hi 
My data are WGS and not contain any normal samples, consist of  tumor and pre-tumor tissues.
For variants calling, used GATK-haplotypecaller.
I understood UNMASC need UMN (pools of unmatched normals). 

Is it possible to use UNMASC for my data? 

thanks !

**Comment by pllittle** [comment]
Hi byeongill,

Thank you for your interest in UNMASC. Do you have any previously sequenced normal WGS samples that underwent similar sequencing protocols and bioinformatic workflows as your tumors? And may I ask are your pre-tumor tissues considered normal? If yes to either question, I believe you could use UNMASC if your variant caller requires both tumor AND normal bams. Having a set of normal read counts paired to each tumor variant call for UNMASC helps screen and classify tumor variants as somatic, germline, artifact.

Hope this helps!

**Comment by byeongill** [comment]
Thanks,

Although the pre-tumor samples are not normal, i will try it as normal (6 samples out of 86 samples). 
Variant calling were performed GATK-haplotypecaller (Not use joint calling)

The main function of "run_UNMASC" need vcf as data.frame which consist of  Qscore, nRD, nAD, tRD, tAD etc.
I can know nRD and nAD in paired tumor samples through matching to variants of pre-tumors.
How do i know nRD and nAD in tumor-only samples ?
