### ISSUE TITLE
No package "smartr"

### ISSUE THREAD

**Issue by byeongill** [pllittle/UNMASC#5]
Hi.
When i install UNMASC in R studio (4.1.3 ver), i got error message.
![image](https://user-images.githubusercontent.com/82578252/161457596-cc59738a-037d-474d-85f8-ddc824aec1d9.png)

I tried to install "smartr", but i couldn't find the package.
Instead, i could find "smartR", so installed it. 
However, same error still appear.

**Comment by byeongill** [comment]
https://github.com/pllittle/smartr

**Comment by pllittle** [comment]
Hi @byeongill,

Thank you for raising the issue. Sorry about the install error. Yes the smartr package is that repository. I've also updated the installation code in the README.md.
