### ISSUE TITLE
Some problems when running prep_UNMASC_VCF

### ISSUE THREAD

**Issue by hfl112** [pllittle/UNMASC#8]
Hi Paul,
After I got all the vep annotations, now I am trying to use pre vcf,
I found several problems in the code, I am not sure whether it's correct to do so:
1. in import_VCFs function:
`if( is.null(FILTER$nDP) || is.numeric(FILTER$nDP) )` should be changed to `if( is.null(FILTER$nDP) || !is.numeric(FILTER$nDP) )  ` ?
2. in import_ANNO function:
there is a "anno = "should be changed to "ANNO=" 
3. a minor problem is when grep CSQ line, you only choose first few lines, For my data, I use almost all chr (because the reference data included all), so I changed n to 5000

But still, I am stuck at  import_ANNO, it looks like there are some problems with my annotation file, which I think is due to a different version of VEP or the custom database? 
![image](https://user-images.githubusercontent.com/33510929/167194205-02fc10c5-91bb-4eb6-9d4d-bf7160a39b16.png)
I found the COSMIC id from my database always startswith "COSV" instead of "COSM". Can you help to look at my vep files? I am not sure what the problem it is.
[test.txt](https://github.com/pllittle/UNMASC/files/8642862/test.txt)

Thank you,
FN

**Comment by hfl112** [comment]
I check the code step by step. I think I know why this happens, but I don't know how to deal with this problem.

some variants in the result if you split INFO by ",", you can't find "COSV" id in the first annotation, but you can find it in the second one.
![image](https://user-images.githubusercontent.com/33510929/167207794-6e7afc0e-4269-483c-b52e-5ff98c714c80.png)

**Comment by pllittle** [comment]
Hi @hfl112,

I've found several bugs in this function that I'm updating based on your txt file. Give me another 30min to debug everything. 

Thank you for your patience and bringing the bugs to my attention.

**Comment by pllittle** [comment]
I've pushed an update, let me know how the import goes. :smile:

**Comment by hfl112** [comment]
> Hi @hfl112,
> 
> I've found several bugs in this function that I'm updating based on your txt file. Give me another 30min to debug everything.
> 
> Thank you for your patience and bringing the bugs to my attention.

Thank you for the speedy reply.
Now, I can successfully run prep_UNMASC_VCF step with first 5000 row of VEP result, but got a problem at run_UNMASC:
% ------------------------------- %
% Welcome to the UNMASC workflow! %
% ------------------------------- %
Fri May  6 15:25:51 2022: Calculate mutID and light filtering ...
Fri May  6 15:25:51 2022: Calculate nVAFs and tVAFs ...
Fri May  6 15:25:51 2022: Import genome files ...
Import/Prep genome files, used for plotting genome position on x-axis.
Error in names(chr_length) <- `*vtmp*` :
  'names' attribute [3] must be the same length as the vector [2]

**Comment by hfl112** [comment]
By the way, I am using Picard mergeVCF to merge all the vcfs and then annotated by VEP, I think it's a little bit incompatible with your code as well. Picard kept all the INFO from strelka, so it might occur some problems when using strsplit in R.

**Comment by pllittle** [comment]
Mmm I see, this merged VCF is convenient for the unique loci and individual read counts but did it accidentally collapse the quality scores? For example wouldn't QSS for one locus in the tumor vary per normal control? So if there are 20 normals, there should be at most 20 unique QSS values. 

`run_UNMASC` is expecting the vcf file to be stacked in rows. So if locus 1 was called a somatic variant by Strelka in 5 out of 20 normals, there should be 5 rows of data in the vcf. The tumor read count and VEP annotation would be identical but the quality score and normal read counts would vary among the 5 rows.

Hopefully this addresses both of your comments. If not, the `run_UNMASC` issue might be related to the format of your bed_centromere and dict_chrom files.

**Comment by hfl112** [comment]
@pllittle , picard indeed collapse the quality score. you can find an example "test.txt" I uploaded in this post. So which method you are using ? 
I have no header in the dict_chrom, should I added?

**Comment by hfl112** [comment]
I just ran `prep_UNMASC_VCF  ` with your new updated code, it's working now. Thanks~

**Comment by hfl112** [comment]
Sorry, I think I didn't understand what you said about stacked vcf in row stuff. 
Are you meaning that I should distribute the vep annotation result to all vcf files and then just "concat" different vcf files as the input_vcf to `prep_UNMASC_VCF `, instead of stacking Normals like T1, N1, T2,N2 ... T5, N5 in the vep.vcf ?

**Comment by pllittle** [comment]
Hi @hfl112,

I apologize, I haven't presented the complete pseudocode for running UNMASC but I'll incorporate it all in eventually. Basically, as inputs, suppose there are 20 VCFs from Strelka imported and row appended together in R (call it `df1`). Then there is the annotation data.frame with genomic loci and prepared annotation columns (call it `df2`) constructed from `prep_UNMASC_VCF()`. Merge these two data.frames together (call it `vcf`) with the required columns for the input `vcf` data.frame from `?run_UNMASC` documentation.

Hope this helps 😃

**Comment by hfl112** [comment]
> 
Ah, I finally got it.
The input of of run_UNMASC is literally not the output vcf of prep_UNMASC_VCF, because I am using a merged vcf for vep annotation, but run_UNSMAC input needed to list all samples' mutations per row. So I need to add those columns like `"CosmicOverlaps", "ThsdG_AF"` back to each sample. Am I correct?😄

**Comment by pllittle** [comment]
That is correct :)

**Comment by hfl112** [comment]
@pllittle , I found it's a little bit wired that in the output vcf of prep_UNMASC_VCF, I only have results from Chr1.
Am I using a wrong input file of prep_UNMASC_VCF?

```
library(smarter)
library(UNMASC)
fout = "unmasc_strelka/2324_PDX_WES"
DAT = read.table("unmasc_strelka/2324_PDX_WES/vcf.list",header = TRUE, sep = '\t')  #this file included all T-Normal paired strelka output
FILTER = list(nDP = 2,tDP = 2,Qscore = 3,contigs = sprintf("chr%s",c(1:22,"X","Y")))
target_fn = "Exome_Targets.hg38.bed"
anno_fn = "2324_PDX_WES.merged.vep.vcf"   #this is a picard merged annotated file
vcf = prep_UNMASC_VCF(fout,DAT,FILTER,target_fn,anno_fn,4)
```
Any suggestion might be helpful~
