### ISSUE TITLE
Errors when running UNMASC

### ISSUE THREAD

**Issue by hfl112** [pllittle/UNMASC#9]
Hi,
I still can't run UNMASC successfully.

1. when I run through UNMSAC::run_UNMASC, I encounter an error like this:
```
Error in xy.coords(x, y, setLab = FALSE) : 'x' and 'y' lengths differ
In addition: Warning messages:
1: In pos/genome$length[one_index] :
  longer object length is not a multiple of shorter object length
2: In pos/genome$length[one_index] + genome$nChr[one_index] :
  longer object length is not a multiple of shorter object length

```
Then I found it was caused by genome_plot in run_nClust, so I modify the code and skip this plotting step, then it worked.

2. After this, I encountered an error "Error in { : task 1 failed - "could not find function "ScanBamParam"" " in strand step.
but I've import the packages from Rsamtools, and I can run `ScanBamParam` in R:
`>  ScanBamParam(which=GRanges(chr,IRanges(start = pos,end = pos)))
class: ScanBamParam
bamFlag (NA unless specified):
bamSimpleCigar: FALSE
bamReverseComplement: FALSE
bamTag:
bamTagFilter:
bamWhich: 1184 ranges
bamWhat:
bamMapqFilter: NA
`
I don't know why UNMASC can't recognize these packages?

Any suggestion for these errors?
Thank you
FN

**Comment by pllittle** [comment]
Hi @hfl112,

1. Could I see what your `bed_centromere` and `dict_chrom` files look like? Could you also generate a summary per chromosome of genomic positions? I just want to get an understanding of the position ranges of your inputs.
2. That is an interesting issue. I haven't encountered that issue in the past analyses I've conducted. Perhaps the issue is related to some newer version of R or the R package `foreach` that requires external package functions to be called like `package::package_function()` within the `foreach` block. I'll look into replicating the issue with newer R and R package versions and re-run some of my own analyses. I'll let you know if I catch similar errors.

**Comment by hfl112** [comment]
1.The centromere and chr.size files are: 
[hg38.chrom.sizes2.txt](https://github.com/pllittle/UNMASC/files/8654598/hg38.chrom.sizes2.txt)
[hg38.centromere.txt](https://github.com/pllittle/UNMASC/files/8654602/hg38.centromere.txt)

2.  I think the error was from `foreach %dopar%` step, it seems mostly it's working, but for some ii, 
the error occurs. I am now trying to find out which line or lines of my input, got this error happened. I will let you know if I got some updates

**Comment by pllittle** [comment]
1. For this one, the chrom sizes looks fine. But for the centromere file, why are there multiple starting and ending intervals per chromosome?
2. Great, yeah it might be that certain rows of the `vcs` object aren't passing expected inputs?

**Comment by hfl112** [comment]
> 

1. I actually download this bed file from ucsc-hgTables, it gives the specific location of each chr. why don't you upload the centrosome.bed file that you are using?
2. Yeah, I guess so.

**Comment by pllittle** [comment]
1. That's fine. I've used [this for hg19](https://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/cytoBand.txt.gz) and [this for hg38](https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/cytoBand.txt.gz). One just needs to subset the rows labeled `acen` and structure the file such that each row is contig, start_centromere, end_centromere.

**Comment by hfl112** [comment]
so, for each chromosome, only 1 centromere region allowed, right ?

**Comment by hfl112** [comment]
Hi @pllittle , I changed the centromere file, and now I can successfully run through UNMASC ! 
Thank you so much for your help~
FN
